bitwarden/authenticator-android

app/build.gradle.kts
gradle/libs.versions.toml

N/A
Remove unused password strength calculator library. …

Remove nulab password strength library

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/edititem/EditItemScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/edititem/EditItemViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/base/util/StringExtensions.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/field/BitwardenPasswordField.kt
app/src/main/res/values/strings.xml

N/A
Ensure that key values are always in Base32 format.
If manually entered key is invalid the user will be notified.
If editing an existing item, key value is checked. If invalid user is notified.
Key input field enforces uppercase alpha input.
Coming soon!
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …

Enforce Base32 key values

---

app/schemas/com.bitwarden.authenticator.data.authenticator.datasource.disk.database.AuthenticatorDatabase/2.json
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/database/AuthenticatorDatabase.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/entity/AuthenticatorItemEntity.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/manager/TotpCodeManagerImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/manager/model/VerificationCodeItem.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/model/UpdateItemRequest.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/edititem/EditItemScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/edititem/EditItemViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/edititem/model/EditItemData.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/VaultVerificationCodeItem.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/model/VerificationCodeDisplayItem.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/VerificationCodeItemExtensions.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/header/BitwardenListHeaderTextWithSupportLabel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/toggle/BitwardenSwitch.kt
app/src/main/res/values/strings.xml

N/A
Allow users to mark items as favorites. Items marked as favorites will be grouped at the top of the item listing screen.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …

Allow users to select favorites

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanViewModel.kt

N/A
Secret code characters are transformed into uppercase when scanned from a QR code. This ensures Base32 evaluation passes when scanned codes are received in lowercase. …

Force scanned codes to uppercase alpha characters

---

gradle/libs.versions.toml

N/A
Declare AndroidX Test Rules dependency version separate from AndroidX Test. …

Separate androidxTest and androidxTestRules dependency versions

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/entity/AuthenticatorItemAlgorithm.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/disk/entity/AuthenticatorItemType.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/ImportManagerImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/ImportFileFormat.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/LastPassJsonExport.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/BitwardenExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/LastPassExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/TwoFasExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/util/ImportFormatExtensions.kt
app/src/main/res/values/strings_non_localized.xml

https://bitwarden.atlassian.net/browse/BWA-14
Allow users to import their unencrypted LastPass exports in JSON format.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …

[BWA-14] Support importing LastPass exports

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt

https://bitwarden.atlassian.net/browse/BWA-22
https://github.com/bitwarden/authenticator-android/issues/88
Prevent the FAB from hiding verification codes at the bottom of the item listing screen.
Resolves #88
- ❓ (`:question:`) for …

[BWA-22] Prevent FAB from hiding verification codes

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
app/src/main/res/values/strings.xml

https://bitwarden.atlassian.net/browse/BWA-18
Add the Backup option to settings. When clicked it describes how app data is backed up using the native device backup mechanisms and provides a link to the official documentation.
- ❓ …

[BWA-18] Add Backup option to settings

---

app/src/main/kotlin/com/bitwarden/authenticator/MainActivity.kt
app/src/main/kotlin/com/bitwarden/authenticator/MainViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSource.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepository.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryImpl.kt

https://bitwarden.atlassian.net/browse/BWA-21
Disable screen capture to prevent capturing sensitive data displayed on screen.
This lays the initial groundwork for allowing users to toggle screen capture from settings.
- ❓ (`:question:`) …

[BWA-21] Disable screen capture

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt

Remove the language selector from Settings since we do not currently have translations for other languages.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …

Remove language switcher

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/manager/model/ExportJsonData.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/BitwardenExportParser.kt

Notify users when importing a Bitwarden file fails.
Modify Bitwarden parser to be more lenient when evaluating OTP keys.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

Fix Bitwarden import

---

app/src/main/res/values/strings_non_localized.xml

Rename the 2FAS import option so that it clearly indicates files should not be password protected.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …

Update 2FAS import option label

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/ImportManagerImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/ExportParseResult.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/ImportDataResult.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/TwoFasJsonExport.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/AegisExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/BitwardenExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/ExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/LastPassExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/TwoFasExportParser.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/importing/ImportingViewModel.kt
app/src/main/res/values/strings.xml

When an import operation fails the user will see a message explaining the failure, when a description is warranted. In paricular this displays a descriptive message when the user attempts to import password protected file from 2FAS or a Bitwarden CSV file.
- 📝 (`:memo:`) or ℹ️ …

Display a descriptive error when import fails

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/AegisExportParser.kt

https://bitwarden.atlassian.net/browse/BWA-41
When importing from Aegis the username will be properly extracted if the name field contains both label and account name.
Coming soon! …

Extract account name from Aegis imports

---

app/src/main/kotlin/com/bitwarden/authenticator/MainActivity.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/util/IntentExtensions.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/util/IntentExtensionsTest.kt

https://bitwarden.atlassian.net/browse/BWA-10
Validate launch intent data before processing in order to prevent DOS attacks from malicious applications.
Coming soon! …

[BWA-10] Sanitize launch intents before processing

---

app/src/main/res/values/strings.xml

Replace `’` character with apostrophe symbol and correctly escape apostrophes.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …

Escape and use correct apostrophe symbol

---

.github/workflows/crowdin-pull.yml
.github/workflows/crowdin-push.yml
crowdin.yml

https://bitwarden.atlassian.net/browse/BWA-27
Trigger sync with Crowdin to keep translations up to date.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …

[BWA-28] Sync translations with Crowdin

---

.github/renovate.json

We don't use Maven here but Gradle, however Renovate needs to resolve Maven dependencies to use at higher levels.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

Add Maven as supported Renovate manager

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/model/FeatureFlag.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/manager/FeatureFlagManagerTest.kt

https://livefront.atlassian.net/browse/BITAU-158
The goal of this PR is to setup a local feature flag for password manager sync.
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

BITAU-158 Add PasswordManagerSync local feature flag

---

app/build.gradle.kts
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/util/AuthenticatorItemEntityExtensions.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/util/SpecialCharWithPrecedenceComparator.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/VerificationCodeItemExtensions.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchViewModel.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/datasource/disk/util/FakeAuthenticatorDiskSource.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/datasource/entity/AuthenticatorItemEntityUtil.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/manager/util/VerificationCodeItemUtil.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryTest.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/util/AuthenticatorItemEntityExtensionsTest.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/util/SpecialCharWithPrecedenceComparatorTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/VerificationCodeItemExtensionsTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchViewModelTest.kt
gradle/libs.versions.toml

https://bitwarden.atlassian.net/browse/BWA-65
Closes #167 
Adds a new comparator to sort items alphabetically, giving precedence to special characters over letters and digits.
This comparator is used to sort items in the item search screen and the main item listing screen.
The comparator also gives priority to lowercase letters when comparing equal letters (e.g., 'a' comes before 'A').
| Before | After |
|--------|--------|
| <img width="372" alt="image" src="https://github.com/user-attachments/assets/17ff289a-9d90-452e-aace-c369af9c3a83"> | <img width="371" alt="image" src="https://github.com/user-attachments/assets/35ee1347-b329-4778-93d5-1bae13f49ab3"> | 
| <img width="372" alt="image" src="https://github.com/user-attachments/assets/aec28b3c-29b7-4080-8f79-c0a97e9374e0"> | <img …

[BWA-65] Sort items alphabetically with special char precedence

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryViewModel.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryViewModelTest.kt

https://bitwarden.atlassian.net/browse/BWA-79
Closes #199 
This commit sanitizes the manual entry code by removing spaces before validation. This ensures that codes with spaces are still considered valid.
| Before | After |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/3273b4f2-8b15-4987-bb96-3c86ad9208aa"/> | <img src="https://github.com/user-attachments/assets/13a46202-80a7-47a6-89b7-e5401d42b3ba"/> | 
- Updated any …

[BWA-79] Sanitize manual entry code before validation

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/annotation/OmitFromCoverage.kt

https://bitwarden.atlassian.net/browse/BWA-91
This commit introduces a new annotation, `OmitFromCoverage`, used to exclude specific classes, files, or functions from test coverage reports. This is intended for non-testable code residing in packages with testable code, and should be used sparingly.
- 📝 …

[BWA-91] Add OmitFromCoverage annotation

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/clipboard/BitwardenClipboardManagerImpl.kt

https://bitwarden.atlassian.net/browse/BWA-90
Closes #191 
This commit removes the use of WorkManager for clearing the clipboard and instead relies on the system's default clipboard timeout.
- 🤔 …

[BWA-90] Remove WorkManager for clipboard clearing

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml

https://livefront.atlassian.net/browse/BITAU-68
We need to specify specific permission per build type. 
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …

BITAU-68 Specify build specific bridge permission in manifest

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/util/IntentExtensions.kt

https://bitwarden.atlassian.net/browse/BWA-10
The commit adds a try-catch block to the `isSuspicious` extension function for `Intent`. This
handles potential exceptions that could occur when accessing the intent's extras in Android 12 or below, and marks the intent as suspicious if an exception is thrown. This change improves the security of the app by preventing unexpected crashes and ensuring that potentially malicious intents are flagged appropriately.
- Communicated to DevOps any deployment …

[BWA-10] Handle exception when checking for suspicious intents

---

app/src/main/kotlin/com/bitwarden/authenticator/data/auth/datasource/disk/AuthDiskSource.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/auth/datasource/disk/AuthDiskSourceImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/di/AuthenticatorBridgeModule.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/util/SymmetricKeyStorageProviderImpl.kt
app/src/test/java/com/bitwarden/authenticator/data/auth/datasource/disk/AuthDiskSourceTest.kt
app/src/test/java/com/bitwarden/authenticator/data/auth/datasource/disk/util/FakeAuthDiskSource.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/util/SymmetricKeyStorageProviderTest.kt

https://livefront.atlassian.net/browse/BITAU-70
The goal of this PR is to store the authenticator sync symmetric key on disk.
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …

BITAU-70 Implement symmetric key storage

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/manager/TotpCodeManagerImpl.kt
app/src/test/java/com/bitwarden/authenticator/data/authenticator/manager/util/TotpCodeManagerTest.kt

N/A
Fix a bug I noticed when moving to the empty state for TOTP items.
N/A …

Fix empty state for totp codes

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/di/AuthenticatorBridgeModule.kt

N/A
I realized that `AuthenticatorBridgeManagerImpl` connects to bridge service and subscribes to lifecycle events in `init`, so I wanted to make sure we aren't instantiating one of those when the feature flag is off. 
N/A
- ❓ …

Return noop bridge manager when password sync feature flag is off

---

fastlane/Fastfile

N/A
I added first UI tests in a [different PR,](https://github.com/bitwarden/authenticator-android/pull/239) and found that we cannot run release variant UI tests on CI. This matches [what we have in the main password manager app.](https://github.com/bitwarden/android/blob/main/fastlane/Fastfile#L108-L113).
I figured a change this specific deserves its own PR!
N/A 
- Updated any necessary documentation (Confluence, contributing docs) or informed the …

Only run debug test variant on CI 

---

app/build.gradle.kts
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/ui/platform/base/BaseComposeTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/base/BaseRobolectricTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModelTest.kt
fastlane/Fastfile

https://livefront.atlassian.net/browse/BITAU-90
The goal of this PR is to add a row to that takes the user to the Bitwarden account security screen so that they can turn on account syncing. If the user doesn't have Bitwarden installed, it should take them to the play store listing. 
<video src="https://github.com/user-attachments/assets/1c86bc2c-16f3-4cc1-89ac-4cecadf88400" width="300" />
- Updated any necessary documentation (Confluence, contributing …

BITAU-90 Add "Sync with Bitwarden App" row to settings

---

.github/workflows/build.yml
fastlane/Fastfile

N/A
We don't need to distribute APKs to firebase, just AAB distribution will suffice. This PR also updates the build workflow to mirror the main app workflow: we only distribute to Firebase when the optional variable is true.
The main difference between the Authenticator setup and the main app setup is the main app distributes to firebase on every merge to main, whereas the Authenticator app still requires a manual action to be run to distribute to firebase.
I've confirmed this workflow properly only uploads AAB files to firebase, no more APKs:
- Used internationalization …

Remove Firebase APK distribution

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/VaultVerificationCodeItem.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/model/SharedCodesDisplayState.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/model/VerificationCodeDisplayItem.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/SharedVerificationCodesStateExtensions.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/VerificationCodeItemExtensions.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListViewModelTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/SharedVerificationCodesStateTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/VerificationCodeItemExtensionsTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/manager/permissions/FakePermissionManager.kt

https://livefront.atlassian.net/browse/BITAU-82
The goal of this PR is to show shared authenticator codes on the item listing screen.
<video src="https://github.com/user-attachments/assets/86168eaf-541e-443b-869d-8370caf8b403" width="300" />
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general …

BITAU-82 Show shared codes on the item listing screen

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/manager/intent/IntentManagerImpl.kt

The `IntentManagerImpl` class is now marked with the `@OmitFromCoverage` annotation, excluding it from code coverage reports.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

Mark IntentManagerImpl as not covered by code coverage

---

app/src/main/AndroidManifest.xml

N/A
The goal here is to make sure syncing works on all our supported API levels. 
I tested on every API level from 34 down to 29. For 30 and 29, we don't support syncing, but those worked as expected where no sync UI was shown. 
Without adding queries, we cannot bind to the `AuthenticatorBridgeService` on certain API levels (namely 31, 32 and 33). [This article](https://swiderski.tech/2021-09-03-android-service-binding-on-api30/) was helpful in discovering this.
N/A
- Communicated to DevOps any deployment …

Add queries to AndroidManifest

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSource.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepository.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/dialog/BitwardenSelectionDialog.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/data/model/DefaultSaveOption.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/util/DefaultSaveOptionExtensions.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/data/platform/datasource/disk/SettingDiskSourceTest.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModelTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/util/DefaultSaveOptionExtensionsTest.kt

https://livefront.atlassian.net/browse/BITAU-181
The goal of this PR is to allow the user to update their default save option from the settings screen.
<video src="https://github.com/user-attachments/assets/34cf7800-53ce-4ebe-912e-cdb2661aa53a" width="300" />
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …

BITAU-181 Allow user to update default save options from settings

---

app/build.gradle.kts

This commit disables the `ExtraTranslation` lint check in addition to the existing `MissingTranslation` check. This is done by adding it to the list of disabled lint checks within the `lint` block of the build configuration.
Unblocks #260 
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …

Disable ExtraTranslation lint check

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/util/SharedVerificationCodesStateExtensions.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/ChooseSaveLocationDialog.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/util/DialogExtensions.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/util/SharedVerificationCodesStateExtensionsTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/FakeQrCodeAnalyzer.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanViewModelTest.kt

https://livefront.atlassian.net/browse/BITAU-89
The goal of this PR is to show the user a dialog asking them where they would like to save QR code they just scanned. The dialog should allow them to save that option as a default. 
- ❓ …

BITAU-89 Show save location dialog on the QR scan screen

---

app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepository.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/di/AuthenticatorRepositoryModule.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/BaseDiskSource.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSource.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepository.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/FirstTimeSyncSnackbarHost.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModel.kt
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryTest.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/datasource/disk/SettingDiskSourceTest.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListViewModelTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt

https://livefront.atlassian.net/browse/BITAU-84
https://livefront.atlassian.net/browse/BITAU-85
The goal of this PR is to show a snackbar anytime a new account is synced with bitwarden.
<video src="https://github.com/user-attachments/assets/a481146a-f34b-4d7b-8d05-afea4b87bf0b" width="300" />
- 📝 (`:memo:`) …

BITAU-84 Show Snackbar the first time a user syncs accounts

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/SaveManualCodeButtons.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryViewModelTest.kt

https://livefront.atlassian.net/browse/BITAU-184
The goal here is to update the manual entry screen to allow for saving to Bitwarden. If the sync is not enabled, the save button should always be save locally. If sync is enabled, the save button should show the primary action (either save local or save to bitwarden) based on what the user has selected as their default save location.
<video src="https://github.com/user-attachments/assets/e71f6661-1322-4bb5-88f2-1193d8765170" width="300" />
- Communicated to …

BITAU-184 Allow user to save to Bitwarden when adding a code manually

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSource.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/disk/SettingsDiskSourceImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepository.kt
app/src/main/kotlin/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryImpl.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModel.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/datasource/disk/SettingDiskSourceTest.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/repository/SettingsRepositoryTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/platform/feature/settings/SettingsViewModelTest.kt

https://livefront.atlassian.net/browse/BITAU-89
The goal here is to have the settings screen observe default save option instead of just grabbing it once.
<video src="https://github.com/user-attachments/assets/8e6a022a-d1e7-4113-baf3-ddd195ccfd8e" width="300" />
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …

BITAU-89 Have SettingsViewModel obsererve DefaultSaveOption

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/FirstTimeSyncSnackbarHost.kt

https://livefront.atlassian.net/browse/BITAU-193
This was showing up very janky in dark theme, now its not!
<video src="https://github.com/user-attachments/assets/18ec06b8-f3a0-4cae-aafb-b05d9816b113" width="300" />
- ❓ (`:question:`) for …

BITAU-193 Make first time sync snackbar correct in dark theme

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/tutorial/TutorialScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/tutorial/TutorialViewModel.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/tutorial/TutorialScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/tutorial/TutorialViewModelTest.kt

[BWA-118](https://bitwarden.atlassian.net/browse/BWA-118)
- Addressed an issue where tutorial text was being cut off in landscape mode on certain devices.
- Refactored the screen to properly support landscape layouts, ensuring the text is fully visible.
- Collaborated with Emily from the design team to align with the landscape designs used in the password manager app's onboarding views.
- Updated any necessary documentation (Confluence, contributing …

BWA-118 - Tutorial text cut off in landscape mode

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModel.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/VaultVerificationCodeItem.kt
app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/model/VaultDropdownMenuAction.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreenTest.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingViewModelTest.kt

[BWA-124](https://bitwarden.atlassian.net/browse/BWA-124)
- Implemented the option to copy an item from the long-press menu. While items could already be copied by clicking on them, adding this functionality to the menu was straightforward.
- Renamed "Copy to Bitwarden" to "Move to Bitwarden" to align with the updated Figma design.
- Refactored the action handling logic to use an enum for dropdown menu actions, consolidating logic and improving maintainability. Added missing tests to cover the new functionality.
https://github.com/user-attachments/assets/9f680a5e-3faf-4acf-bbf1-65663bdf1f86
- Protected functional changes with optionality …

BWA-124 - 'Copy' Option Missing from Long-Press Menu

---

.github/workflows/build.yml
fastlane/Appfile
fastlane/Fastfile

BWA-33
Downloads the `authenticator_play_store-creds.json` file from Azure blob storage and uses it for publishing to the Google Play Store.
Automatically determine the next version name based on git tags.
If the major and minor versions match the current date, increment the revision. Otherwise, start a new version based on the year and month.
Display version name and code in the workflow summary.
Allow overriding version code and name via workflow inputs.
- Communicated to DevOps any deployment …

[BWA-33]: Publish release bundles to Play Store when requested

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/feature/tutorial/TutorialScreen.kt
app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/tutorial/TutorialScreenTest.kt

[BWA-118](https://bitwarden.atlassian.net/browse/BWA-118)
- Portions of the tutorial text are cut off or not visible when the app is rotated to landscape mode during the tutorial.
<video src="https://github.com/user-attachments/assets/cd54c578-f15f-4c0e-b9f9-46546c82ac93"/>
- 📝 (`:memo:`) or ℹ️ …

BWA-118 Tutorial text cut off in landscape mode

---

.github/workflows/test.yml

BWA-141
Fix CodeCov reporting. Action changes `file` property to `files`. …

[BWA-141] Use `files` instead of `file` in codecov action

---

app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/model/FlagKey.kt
app/src/test/java/com/bitwarden/authenticator/data/platform/manager/FlagKeyTest.kt

[BWA-144](https://bitwarden.atlassian.net/browse/BWA-144)
- Update Authenticator Sync feature flag name to `enable-pm-bwa-sync`
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …

BWA-144 - Consolidate feature flags for sync between the Password Manager Authenticator

---

app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/components/card/BitwardenActionCard.kt

[PM-17566](https://bitwarden.atlassian.net/browse/PM-17566)
- The `BitwardenActionCard` wasn't using the `AuthenticatorTheme` so it was showing up as too dark.  Updated the logic to use the theme which fixed the issue.
- ❓ (`:question:`) …

PM-17566 - Authenticator Sync: In Dark theme, the Action card in the Authenticator is too dark

---

fastlane/Fastfile

[PM-16534](https://bitwarden.atlassian.net/browse/PM-16534)
Match Fastfile lanes to recent build.yml changes
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …

[PM-16534] Fix Fastfile lanes

---

fastlane/Fastfile

PM-16534
Once migrated, the authenticator builds must specify the module in the task name to prevent tasks in unrelated modules from executing.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …

[PM-16534] Update gradle invocations to specify authenticator module

---

authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/sdk/AuthenticatorSdkSource.kt
authenticator/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/datasource/sdk/AuthenticatorSdkSourceImpl.kt
authenticator/src/main/res/values/styles.xml
gradle/libs.versions.toml

- Update Bitwarden SDK to `1.0.0-20250213.181812-113`.
- Use `sdk-android-temp` module for the Bitwarden SDK.
- Update the `TotpResponse` import to come from the `com.bitwarden.vault` package instead of `com.bitwarden.core`.
- Change `BaseTheme` parent to `Theme.AppCompat.Light.NoActionBar`
- …

Update Bitwarden SDK and use `sdk-android-temp`
