- app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/manager/biometrics/BiometricsManagerImpl.kt
N/A
Use valid authenticators when running on Android Q and below.
Android Q does not support the combination of `BIOMETRICS_STRONG or DEVICE_CREDENTIAL` so `BIOMETRICS_WEAK or DEVICE_CREDENTIAL` is used instead.
- ❓ (`:question:`) for …
> Use valid authenticators on Android Q and below

- fastlane/Fastfile
N/A
Dynamically determine version name when building from Actions.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
> Fix version name generation

- .github/ISSUE_TEMPLATE/bug.yml
N/A
Define a template for bug reports.
- 🎨 (`:art:`) for …
> Define issue template for bugs

- app/src/main/AndroidManifest.xml
https://bitwarden.atlassian.net/browse/BWA-9
Mitigate potential task hijacking vulnerability by declaring an empty task affinity in the manifest.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open …
> [BWA-9] Set task affinity to mitigate task hijacking

- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/ImportManagerImpl.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/AegisJsonExport.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/ImportFileFormat.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/AegisExportParser.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/util/ImportFormatExtensions.kt
- app/src/main/res/values/strings_non_localized.xml
https://bitwarden.atlassian.net/browse/BWA-5
Allow users to import their Aegis entries.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …
> [BWA-5] Support importing Aegis exports

- .github/renovate.json
IssuerTracker: https://issuetracker.google.com/issues/336842920
Add AndroidX Lifecycle dependencies to the Kotlin renovate group so they maintain compatibility with Compose counterparts.
- 🤔 (`:thinking:`) …
> Add `androidx.lifecycle` dependencies to kotlin group

- .checkmarx/config.yml
Adds a Checkmarx config so that tests are excluded from scans. …
> Checkmarx configuration

- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/model/TwoFasJsonExport.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/manager/imports/parsers/TwoFasExportParser.kt
Improve reliability of 2FAS import. Deserialization is more lenient when JSON contains missing properties.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
> Improve 2FAS import

- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/util/VerificationCodeItemExtensions.kt
https://bitwarden.atlassian.net/browse/BWA-32
Sort verification codes by their Issuer on the item listing screen.
Coming soon!
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not …
> [BWA-32] Sort verification codes by issuer

- .github/renovate.json
Configures an explicit GitHub Packages reference for the SDK as the Gradle settings aren't invoked.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a …
> Configure registry URL for SDK

- .github/renovate.json
Removes the Renovate customizations that tested SDK access. …
> Remove Renovate SDK customizations

- app/build.gradle.kts
Adds better wildcarding of test paths as they'll live amongst the source files.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
> Adjust Sonar scan paths

- app/build.gradle.kts
Excludes tests from Sonar as a recommended best practice. …
> Exclude tests from Sonar

- .github/workflows/crowdin-pull.yml
- .github/workflows/crowdin-push.yml
BWA-28
Read Crowdin API token from GitHub secrets.
- 🎨 …
> [BWA-28] Read Crowdin API token from secrets

- app/build.gradle.kts
https://bitwarden.atlassian.net/browse/BWA-52
Disable "MissingTranslations" lint error to prevent build failures when new string resources are added to the default file. …
> [BWA-52] Disable MissingTranslation lint error

- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/network/di/PlatformNetworkModule.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/datasource/network/serializer/ZonedDateTimeSerializer.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/platform/util/JsonExtensions.kt
- app/src/test/java/com/bitwarden/authenticator/data/platform/datasource/network/serializer/ZonedDateTimeSerializerTest.kt
- app/src/test/java/com/bitwarden/authenticator/data/platform/util/JsonExtensionsTest.kt
https://bitwarden.atlassian.net/browse/BWA-56
Add platform network module for deserializing JSON.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
> [BWA-56] Add network module

- app/build.gradle.kts
- detekt-baseline.xml
- detekt-config.yml
- gradle/libs.versions.toml
https://bitwarden.atlassian.net/browse/BWA-60
Configure detekt to perform lint and formatting checks.
`detekt-baseline` is generated to prevent existing issues from breaking the build on `main`. Pre-existing issues will be resolved in subsequent pull requests.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …
> [BWA-60] Configure detekt scanning

- app/src/main/AndroidManifest.xml
https://livefront.atlassian.net/browse/BITAU-67
The goal of this PR is to add the custom permission to the manifest.
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
> BITAU-67 Add custom authenticator bridge permission to manifest

- app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepository.kt
- app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
N/A
Just removing some unused code before continuing!
- …
> remove unused getAuthCodeFlow()

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
N/A
This PR updates the Android Gradle Plugin (v8.7.0) and the Gradle Wrapper (v8.10.2) to their latest versions.
Release Notes:
* [AGP](https://developer.android.com/build/releases/gradle-plugin#android-gradle-plugin-8.7.0)
* [Gradle](https://docs.gradle.org/8.10.2/release-notes.html)
- 📝 (`:memo:`) or ℹ️ …
> Update Android Gradle plugin and Gradle wrapper

- app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryImpl.kt
- app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/AuthenticatorRepositoryTest.kt
N/A
The goal of this PR is to use the correct feature flag. 
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
> Use correct feature for syncing with Bitwarden

- app/build.gradle.kts
- app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/di/AuthenticatorBridgeModule.kt
https://livefront.atlassian.net/browse/BITAU-68
Specify correct connection type based on build type. 
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed …
> BITAU-68 Specify correct authenticatorbridge connection type 

- .github/workflows/build.yml
N/A
Of course I forgot a closing paren 🤦 
N/A
- 🎨 …
> Add closing paren

- fastlane/Fastfile
N/A
Auto distribute firebase builds to Livefront team. 
N/A
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
> Distribute Firebase builds to `livefront` group.

- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/itemlisting/ItemListingScreen.kt
- app/src/main/res/values/strings.xml
https://livefront.atlassian.net/browse/BITAU-76
Simple copy update that came back from QA!
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …
> BITAU-76 Update copy on download Bitwarden action card

- app/src/main/kotlin/com/bitwarden/authenticator/data/authenticator/repository/util/SharedVerificationCodesStateExtensions.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchScreen.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchViewModel.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/VaultVerificationCodeItem.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/search/handlers/SearchHandlers.kt
- app/src/test/java/com/bitwarden/authenticator/data/authenticator/repository/util/SharedVerificationCodesStateExtensionsTest.kt
- app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/search/ItemSearchViewModelTest.kt
https://livefront.atlassian.net/browse/BITAU-178
The goal here is to get Shared codes to show up on the search screen.
<video src="https://github.com/user-attachments/assets/0f2dddbd-93af-4848-a564-0eb24d8bd661" width="300" />
- ❓ …
> BITAU-178 Show shared codes on the search screen

- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreen.kt
- app/src/main/res/values/strings.xml
https://livefront.atlassian.net/browse/BITAU-198
Just addressing a bit of copy feedback that came from Emily.
| Design | Impl |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/008ec8e2-99fc-4928-b6e8-8500a9051b05" width="300" /> | <img src="https://github.com/user-attachments/assets/97e50c4f-65ee-4ba8-9288-6d29b57704a5" width="300" /> |
- Updated any necessary documentation (Confluence, contributing docs) or informed the …
> BITAU-198 Update some copy on the manual entry screen

- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/SaveManualCodeButtons.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/ChooseSaveLocationDialog.kt
- app/src/main/kotlin/com/bitwarden/authenticator/ui/platform/util/DefaultSaveOptionExtensions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/manualcodeentry/ManualCodeEntryScreenTest.kt
- app/src/test/java/com/bitwarden/authenticator/ui/authenticator/feature/qrcodescan/QrCodeScanScreenTest.kt
- app/src/test/java/com/bitwarden/authenticator/ui/platform/util/DefaultSaveOptionExtensionsTest.kt
https://livefront.atlassian.net/browse/BITAU-197
The goal is to update copy per Emily's feedback!
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
> BITAU-197 Update copy in all Save to Bitwarden scenarios

- .github/workflows/crowdin-pull.yml
[BRE-471](https://bitwarden.atlassian.net/browse/BRE-471)
This PR updates the `Crowdin Sync`  workflow to create the PR using a temporary token generated by our BW-GHApp. …
> [BRE-471] Update to use app generated token

- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
https://bitwarden.atlassian.net/browse/PM-16391
- Update Gradle to 8.10.2.
- Update Android Gradle Plugin to 8.8.0.
[Release notes!](https://developer.android.com/build/releases/gradle-plugin)
- 🤔 …
> [PM-16391] Update Gradle and Android Gradle Plugin

- fastlane/Fastfile
[PM-16534](https://bitwarden.atlassian.net/browse/PM-16534)
Typo. 🤦🏾 
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
> [PM-16534] Fix fastfile typo

- .github/workflows/test.yml
[PM-16534](https://bitwarden.atlassian.net/browse/PM-16534)
Update test.yml ahead of #342 
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could …
> [PM-16534] Update test lane name

- .github/workflows/build.yml
- .github/workflows/test.yml
- fastlane/Fastfile
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) …
> [PM-16534] Update fastfile check lane
